### User Registeration

POST http://localhost:8000/api/user/registeration
content-type: application/json

{
  "name":"Ahzam Ahmed",
  "email":"test4 @test.com",
  "password":"1234",
  "password_confirmation":"1234",
  "tc":true
}

### User Login

POST http://localhost:8000/api/user/login
content-type: application/json

{  
  "email":"test4 @test.com",
  "password":"1234"
}