### User Registeration
POST http://localhost:8000/api/user/registeration
content-type: application/json

{
  "name":"Ahzam Ahmed",
  "email":"test5@test.com",
  "password":"1234",
  "password_confirmation":"1234",
  "tc":true
}

### User Login
POST http://localhost:8000/api/user/login
content-type: application/json

{  
  "email":"test4 @test.com",
  "password":"12345"
}

### User Change Password
POST http://localhost:8000/api/user/change-password
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MzhiNmYzYTk2ZTQyNmQxMGI1MWM5NjUiLCJpYXQiOjE2NzA1MTYwOTQsImV4cCI6MTkzMjMwODA5NH0.Gffxk70IUY4ui9wSMUR7OrpPPIyQHthdVDvxpOy0vpg

{  
  "oldPassword":"1234",
  "newPassword":"12345",
  "confirmPassword":"12345"
}

### User Profile
GET http://localhost:8000/api/user/user-profile
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MzhiNmYzYTk2ZTQyNmQxMGI1MWM5NjUiLCJpYXQiOjE2NzA1MTYwOTQsImV4cCI6MTkzMjMwODA5NH0.Gffxk70IUY4ui9wSMUR7OrpPPIyQHthdVDvxpOy0vpg



### Password Reset Email
POST http://localhost:8000/api/user/password-reset-email
content-type: application/json

{  
  "email": "test4 @test.com"
}