### User Registeration
POST http://localhost:8000/api/user/registeration
content-type: application/json

{
  "name":"Ahzam Ahmed",
  "email":"test5@test.com",
  "password":"1234",
  "password_confirmation":"1234",
  "tc":true
}

### User Login
POST http://localhost:8000/api/user/login
content-type: application/json

{  
  "email":"test4 @test.com",
  "password":"12345"
}

### User Change Password
POST http://localhost:8000/api/user/changepassword
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MzhiNmYzYTk2ZTQyNmQxMGI1MWM5NjUiLCJpYXQiOjE2NzAyNTg4MDYsImV4cCI6MTY3MDM0NTIwNn0.n_X9EstdyRlkyUnBJmE3BNTMpbIlDGEcFDfTETiSKWc

{  
  "oldPassword":"1234",
  "newPassword":"12345",
  "confirmPassword":"12345"
}

### User Profile
GET http://localhost:8000/api/user/userprofile
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MzhiNmYzYTk2ZTQyNmQxMGI1MWM5NjUiLCJpYXQiOjE2NzAzNTI5ODgsImV4cCI6MTY3MDQzOTM4OH0.gWtb0rRJZ3wXujRmnc5XGEtYEaIaLUbSqfhH75uy3Wk